import React, { useEffect, useState } from 'react';
import { GeneratedImage } from '../types';
import { getPublicFeed } from '../services/firebase';
import { Loader2 } from 'lucide-react';

const CommunityFeed: React.FC = () => {
  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchFeed();
  }, []);

  const fetchFeed = async () => {
    setLoading(true);
    const feed = await getPublicFeed();
    setImages(feed);
    setLoading(false);
  };

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Loader2 className="animate-spin text-indigo-600" size={32} />
      </div>
    );
  }

  return (
    <div className="mt-16">
      <h2 className="text-2xl font-bold text-slate-900 mb-8 text-center">Community Creations</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {images.map((img) => (
          <div key={img.id} className="group relative rounded-xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 bg-white border border-slate-100 h-64 md:h-72">
            <img 
              src={img.imageUrl} 
              alt={img.prompt} 
              className="w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-500"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 p-4 flex flex-col justify-end">
              <p className="text-white text-sm font-medium line-clamp-2">{img.prompt}</p>
              <div className="flex justify-between items-center mt-2">
                 <span className="text-xs text-slate-300">Generated by Community</span>
                 {img.style && <span className="text-xs px-2 py-0.5 bg-white/20 rounded-full text-white backdrop-blur-sm">{img.style}</span>}
              </div>
            </div>
          </div>
        ))}
      </div>
      {images.length === 0 && (
        <p className="text-center text-slate-500">No community images yet. Be the first to create!</p>
      )}
    </div>
  );
};

export default CommunityFeed;
